### ISSUE TITLE
Make aws-sdk an optional dependency

### ISSUE THREAD

**Issue by temyers** [MechanicalRock/beady-eye#17]
At the moment, aws-sdk is packaged as a node dependency.  This unnecessarily bloats it's usage when packaged in a Lambda function.

Options:
* Use [codependency](https://www.npmjs.com/package/codependency) to specify as an optional dependency
* Specify `aws-sdk` as a development dependency.  This will cause issues if it is not used in Lambda functions, where the aws-sdk is already pre-packaged.

The current workaround is for the client to explicitly exclude it from packaging.
Example (Serverless Framework serverless.yml snippet)
```
  my-connection-test:
    handler:  src/connectionTester.connect
    package:
      # only include connection tester
      exclude:
        - src/**
        - node_modules/**
      include:
        - src/connectionTester.js
        - node_modules/beady-eye/**
       # exclude aws-sdk from packaging
        - '!node_modules/beady-eye/node_modules/aws-sdk/**'
```
